# Generated by Django 2.2 on 2021-03-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=17)),
                ('lastName', models.CharField(max_length=17)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=17)),
                ('charClass', models.CharField(max_length=17)),
                ('level', models.IntegerField()),
                ('background', models.CharField(max_length=17)),
                ('race', models.CharField(max_length=17)),
                ('ac', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('strSave', models.BooleanField()),
                ('dexSave', models.BooleanField()),
                ('conSave', models.BooleanField()),
                ('intSave', models.BooleanField()),
                ('wisSave', models.BooleanField()),
                ('chaSave', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='dragonchosen.User')),
            ],
        ),
    ]
