# Generated by Django 2.2 on 2021-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonchosen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strSave',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
