# Generated by Django 2.2 on 2021-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonchosen', '0005_auto_20210401_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='level',
            field=models.CharField(max_length=8),
        ),
    ]
