# Generated by Django 2.2 on 2021-04-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonchosen', '0007_hero_nagaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parenthetical', models.TextField(blank=True)),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageResistances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.IntegerField()),
                ('hp', models.CharField(max_length=10)),
                ('hpAvg', models.IntegerField()),
                ('source', models.CharField(max_length=6)),
                ('pageNumber', models.CharField(max_length=6)),
                ('creatureType', models.CharField(max_length=12)),
                ('intBonus', models.IntegerField()),
                ('conBonus', models.IntegerField()),
                ('strBonus', models.IntegerField()),
                ('wisBonus', models.IntegerField()),
                ('chaBonus', models.IntegerField()),
                ('dexBonus', models.IntegerField()),
                ('intValue', models.IntegerField()),
                ('wisValue', models.IntegerField()),
                ('chaValue', models.IntegerField()),
                ('dexValue', models.IntegerField()),
                ('strValue', models.IntegerField()),
                ('conValue', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monActions', models.ManyToManyField(related_name='monOwners', to='dragonchosen.Actions')),
                ('monDamageResistances', models.ManyToManyField(related_name='monOwners', to='dragonchosen.DamageResistances')),
                ('monSaves', models.ManyToManyField(related_name='monOwners', to='dragonchosen.Saves')),
                ('monSenses', models.ManyToManyField(related_name='monOwners', to='dragonchosen.Senses')),
                ('monSpeeds', models.ManyToManyField(related_name='monOwners', to='dragonchosen.Speeds')),
                ('monTraits', models.ManyToManyField(related_name='monOwners', to='dragonchosen.Traits')),
            ],
        ),
    ]
