# Generated by Django 2.2 on 2021-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonchosen', '0008_actions_damageresistances_monster_saves_senses_speeds_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(default='noName', max_length=25),
            preserve_default=False,
        ),
    ]
